version: '1'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    restart: always
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=@admin123
    ports:
      - "1433:1433"
    volumes:
      - ./Mssql:/var/opt/mssql

volumes:
    Mssql: